resources:
  - ../../base/namespaces
  - ../../base/vpa
  - ../../base/goldilocks
  - ../../base/kyverno-policies-mutate
  - ../../base/kyverno-policies-generate
  - ../../base/kyverno-policies-audit
  - ../../base/vpa-exporter
