apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpa-recommendation-exporter-git
  namespace: goldilocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: vpa-recommendation-exporter-git
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "x-access-token"
  data:
    - secretKey: token
      remoteRef:
        key: goldilocks-vpa-write-token
        property: value
