apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vpa-selfsigned
  namespace: kube-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-webhook-tls
  namespace: kube-system
spec:
  secretName: vpa-tls-certs
  dnsNames:
    - vpa-webhook.kube-system.svc
  issuerRef:
    name: vpa-selfsigned
    kind: Issuer
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
