resources:
  - admission-controller-deployment.yaml
  - admission-controller-service.yaml
  - cert-manager.yaml
  - recommender-deployment.yaml
  - updater-deployment.yaml
  - vpa-rbac.yaml
  - vpa-v1-crd-gen.yaml
patchesStrategicMerge:
  - patch-admission-controller-tls-args.yaml
