apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-goldilocks-label-by-project
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: label-goldilocks-namespaces
      match:
        resources:
          kinds:
            - Namespace
          selector:
            matchExpressions:
              - key: field.cattle.io/projectId
                operator: In
                values:
                  - "applications"
                  - "infrastructure"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              goldilocks.fairwinds.com/enabled: "true"
