apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-goldilocks-label-by-project
spec:
  rules:
    - name: label-goldilocks-namespaces
      match:
        resources:
          kinds:
            - Namespace
          selector:
            matchExpressions:
              - key: field.cattle.io/projectId
                operator: In
                values:
                  - infrastructure
                  - applications
      exclude:
        any:
          - resources:
              names:
                - argocd
                - nvidia
          - resources:
              selector:
                matchLabels:
                  platform.suncoast.systems/goldilocks: "disabled"
          - resources:
              selector:
                matchLabels:
                  platform.suncoast.systems/vpa-exclude: "true"
      mutate:
        mutateExistingOnPolicyUpdate: true
        targets:
          - apiVersion: v1
            kind: Namespace
        patchStrategicMerge:
          metadata:
            labels:
              platform.suncoast.systems/autosize: "enabled"
              goldilocks.fairwinds.com/enabled: "true"
