resources:
  - critical-workloads-require-resources.yaml
  - exclude-ollama-from-vpa.yaml
  - ollama-require-gpu-node.yaml
  - suspend-vpa-patch-pipeline.yaml
  - nvidia-toolkit-driver-ready-rootfix.yaml
  - nvidia-validator-driver-ready-rootfix.yaml
