apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: system-namespace-vpa-exclude
spec:
  background: true
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: label-system-namespaces
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchExpressions:
                  - key: field.cattle.io/projectId
                    operator: NotIn
                    values:
                      - infrastructure
                      - applications
          - resources:
              kinds:
                - Namespace
              selector:
                matchExpressions:
                  - key: field.cattle.io/projectId
                    operator: DoesNotExist
      mutate:
        targets:
          - apiVersion: v1
            kind: Namespace
            name: "{{request.object.metadata.name}}"
        patchStrategicMerge:
          metadata:
            labels:
              platform.suncoast.systems/system: "true"
              platform.suncoast.systems/vpa-exclude: "true"
            annotations:
              platform.suncoast.systems/vpa-exclude: "true"
      skipBackgroundRequests: false
    - name: clear-system-labels-in-app-projects
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchExpressions:
                  - key: field.cattle.io/projectId
                    operator: In
                    values:
                      - infrastructure
                      - applications
      mutate:
        targets:
          - apiVersion: v1
            kind: Namespace
            name: "{{request.object.metadata.name}}"
        patchStrategicMerge:
          metadata:
            labels:
              platform.suncoast.systems/system: null
              platform.suncoast.systems/vpa-exclude: null
            annotations:
              platform.suncoast.systems/vpa-exclude: null
      skipBackgroundRequests: false
    - name: annotate-system-projects
      match:
        any:
          - resources:
              kinds:
                - management.cattle.io/v3/Project
      preconditions:
        all:
          - key: "{{ request.object.metadata.name }}"
            operator: NotIn
            value:
              - applications
              - infrastructure
      mutate:
        targets:
          - apiVersion: management.cattle.io/v3
            kind: Project
            name: "{{request.object.metadata.name}}"
        patchStrategicMerge:
          metadata:
            annotations:
              platform.suncoast.systems/vpa-exclude: "true"
      skipBackgroundRequests: false
