apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-pdbs
spec:
  rules:
    - name: generate-pdb-for-deployments
      match:
        resources:
          kinds:
            - Deployment
          namespaceSelector:
            matchLabels:
              platform.suncoast.systems/autosize: "enabled"
      exclude:
        any:
          - resources:
              selector:
                matchLabels:
                  platform.suncoast.systems/pdb-exclude: "true"
          - resources:
              namespaceSelector:
                matchLabels:
                  platform.suncoast.systems/pdb-exclude: "true"
      preconditions:
        all:
          - key: "{{ request.object.spec.replicas || 1 }}"
            operator: GreaterThanOrEquals
            value: 2
      generate:
        apiVersion: policy/v1
        kind: PodDisruptionBudget
        name: "{{request.object.metadata.name}}-pdb"
        namespace: "{{request.object.metadata.namespace}}"
        synchronize: true
        generateExisting: true
        data:
          metadata:
            labels:
              app.kubernetes.io/managed-by: kyverno
          spec:
            maxUnavailable: 1
            selector:
              matchLabels: "{{request.object.spec.selector.matchLabels}}"
      skipBackgroundRequests: false
    - name: generate-pdb-for-statefulsets
      match:
        resources:
          kinds:
            - StatefulSet
          namespaceSelector:
            matchLabels:
              platform.suncoast.systems/autosize: "enabled"
      exclude:
        any:
          - resources:
              selector:
                matchLabels:
                  platform.suncoast.systems/pdb-exclude: "true"
          - resources:
              namespaceSelector:
                matchLabels:
                  platform.suncoast.systems/pdb-exclude: "true"
      preconditions:
        all:
          - key: "{{ request.object.spec.replicas || 1 }}"
            operator: GreaterThanOrEquals
            value: 2
      generate:
        apiVersion: policy/v1
        kind: PodDisruptionBudget
        name: "{{request.object.metadata.name}}-pdb"
        namespace: "{{request.object.metadata.namespace}}"
        synchronize: true
        generateExisting: true
        data:
          metadata:
            labels:
              app.kubernetes.io/managed-by: kyverno
          spec:
            minAvailable: 1
            selector:
              matchLabels: "{{request.object.spec.selector.matchLabels}}"
      skipBackgroundRequests: false
