apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-vpa-autosize
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
spec:
  rules:
    - name: generate-vpa-for-deployments
      match:
        resources:
          kinds:
            - Deployment
          namespaceSelector:
            matchLabels:
              platform.suncoast.systems/autosize: "enabled"
      exclude:
        any:
          - resources:
              selector:
                matchLabels:
                  platform.suncoast.systems/vpa-exclude: "true"
          - resources:
              namespaceSelector:
                matchLabels:
                  platform.suncoast.systems/vpa-exclude: "true"
          - resources:
              namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: kyverno
      generate:
        apiVersion: autoscaling.k8s.io/v1
        kind: VerticalPodAutoscaler
        name: "goldilocks-{{request.object.metadata.name}}"
        namespace: "{{request.object.metadata.namespace}}"
        synchronize: true
        generateExisting: true
        data:
          metadata:
            labels:
              app.kubernetes.io/managed-by: kyverno
          spec:
            targetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: "{{request.object.metadata.name}}"
            updatePolicy:
              updateMode: "InPlaceOrRecreate"
            resourcePolicy:
              containerPolicies:
                - containerName: "*"
                  controlledValues: "RequestsAndLimits"
                  minAllowed:
                    cpu: "200m"
                    memory: "256Mi"
                  maxAllowed:
                    cpu: "1"
                    memory: "3Gi"
      skipBackgroundRequests: false
    - name: generate-vpa-for-statefulsets
      match:
        resources:
          kinds:
            - StatefulSet
          namespaceSelector:
            matchLabels:
              platform.suncoast.systems/autosize: "enabled"
      exclude:
        any:
          - resources:
              selector:
                matchLabels:
                  platform.suncoast.systems/vpa-exclude: "true"
          - resources:
              namespaceSelector:
                matchLabels:
                  platform.suncoast.systems/vpa-exclude: "true"
          - resources:
              namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: kyverno
      generate:
        apiVersion: autoscaling.k8s.io/v1
        kind: VerticalPodAutoscaler
        name: "goldilocks-{{request.object.metadata.name}}"
        namespace: "{{request.object.metadata.namespace}}"
        synchronize: true
        generateExisting: true
        data:
          metadata:
            labels:
              app.kubernetes.io/managed-by: kyverno
          spec:
            targetRef:
              apiVersion: apps/v1
              kind: StatefulSet
              name: "{{request.object.metadata.name}}"
            updatePolicy:
              updateMode: "InPlaceOrRecreate"
            resourcePolicy:
              containerPolicies:
                - containerName: "*"
                  controlledValues: "RequestsAndLimits"
                  minAllowed:
                    cpu: "200m"
                    memory: "256Mi"
                  maxAllowed:
                    cpu: "1"
                    memory: "3Gi"
      skipBackgroundRequests: false
